name: proyecto_ubb
description: "Proyecto de título UBB 2024"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 23
