name: proyecto_ubb
description: "Proyecto de título UBB 2024"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner:
    git:
      url: https://github.com/wrteam-anish/flutter_barcode_scanner.git
      ref: master
  flutter_launcher_icons: ^0.13.1
  openfoodfacts: ^3.12.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 23
